# Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.

"""
Generate CMake CTest definitions from YAML test parameters.

Usage:
    python3 auto_generate_tests.py [--all | --api APINAME] <output_dir>

Examples:
    python3 auto_generate_tests.py --api getrf /path/to/output
    python3 auto_generate_tests.py --all /path/to/output
"""

import argparse
import itertools
import sys
import yaml
from pathlib import Path

def check_yaml_api_definition_keys(api_name, api_def):
    """Validate that API definition has required keys.

    Args:
        api_name: Name of the API being validated.
        api_def: Dictionary containing the API definition with required keys.

    Returns:
        True if validation passes.

    Raises:
        ValueError: If required keys are missing from the API definition.
    """
    required_keys = ['param_order', 'description', 'api_group']
    missing_keys = [key for key in required_keys if key not in api_def]
    if missing_keys:
        raise ValueError(
            f"API '{api_name}' missing required keys: {', '.join(missing_keys)}"
        )
    return True


def get_leading_dimension_params(param_order):
    """Detect leading dimension parameters in param_order.

    Args:
        param_order: Ordered list of parameter names.

    Returns:
        List of parameter names that start with 'ld' (e.g., lda, ldb, ldab).
    """
    leading_dim_params = []
    for param in param_order:
        if param.startswith('ld'):
            leading_dim_params.append(param)
    return leading_dim_params


def validate_path_definition(path, path_index, param_order):
    """Validate that a test path definition has required keys and parameters.

    Args:
        path: Dictionary describing a test path definition.
        path_index: Index of the path within the list (for error messages).
        param_order: Ordered list of parameter names required for the API.

    Returns:
        True if validation passes.

    Raises:
        ValueError: If required keys or parameters are missing or malformed.
    """
    if 'name' not in path:
        raise ValueError(
            f"Path at index {path_index} missing required key: 'name'"
        )
    if 'params' not in path:
        raise ValueError(
            f"Path '{path.get('name', f'index_{path_index}')}' "
            f"missing required key: 'params'"
        )

    params = path['params']

    # Check if square parameter is present (will generate m, n, and leading dimension params)
    has_square = 'square' in params
    if has_square:
        # Validate square format
        square_value = params['square']
        if not isinstance(square_value, dict) or 'range' not in square_value:
            raise ValueError(
                f"Path '{path['name']}' parameter 'square' "
                f"must be a dict with 'range' key"
            )

        range_spec = square_value['range']
        if not isinstance(range_spec, list) or len(range_spec) != 2:
            raise ValueError(
                f"Path '{path['name']}' parameter 'square' "
                f"has invalid range format"
            )

        start, end = range_spec
        try:
            start_int, end_int = int(start), int(end)
        except (ValueError, TypeError):
            raise ValueError(
                f"Path '{path['name']}' parameter 'square' "
                f"has invalid range format"
            )

        if start_int > end_int:
            raise ValueError(
                f"Path '{path['name']}' parameter 'square' "
                f"has invalid range: start > end"
            )

    # Check for missing parameters (but allow range specifications
    # and square parameter)
    missing_params = []
    # Parameters that square will generate: m, n, k, ihi,
    # and any leading dimension parameters
    leading_dim_params = get_leading_dimension_params(param_order)
    square_generated_params = {'m', 'n', 'k', 'ihi'} | set(leading_dim_params)

    for p in param_order:
        if p not in params:
            # If square is present and this parameter would be generated by square, don't report as missing
            if has_square and p in square_generated_params:
                continue
            missing_params.append(p)
        else:
            # Check if it's a valid range format or regular value
            param_value = params[p]
            if isinstance(param_value, dict) and 'range' not in param_value:
                raise ValueError(
                    f"Path '{path['name']}' parameter '{p}' "
                    f"has invalid format"
                )

    if missing_params:
        raise ValueError(
            f"Path '{path['name']}' missing required parameters: "
            f"{', '.join(missing_params)}"
        )
    return True


def load_global_config(script_dir):
    """Load global configuration from auto_generate_label_groups.yaml.

    Args:
        script_dir: Directory where the script and YAML config live.

    Returns:
        Dictionary with label groups, size thresholds, and auto-assign groups.
    """
    label_groups_file = script_dir / "auto_generate_label_groups.yaml"
    config = {
        'label_groups': {},
        'size_thresholds': None,
        'auto_assign_groups': {}
    }

    if label_groups_file.exists():
        try:
            with open(label_groups_file, 'r') as f:
                global_data = yaml.safe_load(f)
                if global_data:
                    config['label_groups'] = global_data.get('label_groups', {})
                    config['size_thresholds'] = global_data.get('size_thresholds')
                    config['auto_assign_groups'] = global_data.get('auto_assign_groups', {})
        except (yaml.YAMLError, IOError) as e:
            print(
                f"Warning: Failed to load auto_generate_label_groups.yaml: {e}",
                file=sys.stderr
            )

    return config


def evaluate_size_label(params, size_thresholds):
    """Evaluate size label based on parameter values and thresholds.

    Args:
        params: Dictionary of expanded parameter values for a test.
        size_thresholds: Threshold configuration dict (small/medium).

    Returns:
        Size label string ('small_size', 'medium_size', 'large_size') or None.
    """
    if not size_thresholds:
        return None

    param_name = size_thresholds.get('parameter', 'max')
    small_threshold = size_thresholds.get('small')
    medium_threshold = size_thresholds.get('medium')

    if small_threshold is None or medium_threshold is None:
        return None

    # Get the value to check
    if param_name == 'max':
        # Check max of m and n if both exist
        m_val = params.get('m')
        n_val = params.get('n')
        if m_val is not None and n_val is not None:
            value = max(m_val, n_val)
        elif n_val is not None:
            value = n_val
        elif m_val is not None:
            value = m_val
        else:
            return None
    elif param_name in params:
        value = params[param_name]
    else:
        return None

    # Evaluate thresholds
    try:
        value = int(value)
        if value < small_threshold:
            return 'small_size'
        elif value < medium_threshold:
            return 'medium_size'
        else:
            return 'large_size'
    except (ValueError, TypeError):
        return None


def auto_assign_group_labels(size_label, auto_assign_groups):
    """Auto-assign group labels based on size label.

    Args:
        size_label: Size label (small_size/medium_size/large_size) or None.
        auto_assign_groups: Mapping of group name to size labels list.

    Returns:
        List of group labels to apply.
    """
    group_labels = []
    for group_name, size_labels in auto_assign_groups.items():
        if size_label in size_labels:
            group_labels.append(group_name)
    return group_labels


def expand_label_groups(label_list, label_groups):
    """Expand label groups to their constituent labels.

    Args:
        label_list: List of labels and/or group names.
        label_groups: Mapping of group name to list of labels.

    Returns:
        Expanded list of labels including group members.
    """
    expanded = []
    for label in label_list:
        if label in label_groups:
            expanded.append(label)
            expanded.extend(label_groups[label])
        else:
            expanded.append(label)
    return expanded


def expand_param_ranges(params, param_order):
    """Expand parameter ranges into individual parameter sets.

    Supports formats:
    1. Dictionary format: {m: {range: [1, 16]}, n: {range: [1, 16]}}
    2. String format: {m: "1-16", n: "1-16"}
    3. Square format: {square: {range: [1, 16]}} sets m, n, and leading dimensions.

    Args:
        params: Dictionary of parameter values/ranges from YAML.
        param_order: Ordered list of parameters used to generate combinations.

    Returns:
        List of expanded parameter dictionaries (one per combination).

    Raises:
        ValueError: If a range specification is malformed.
    """
    # Check for square range format (m=n=leading_dimension_params)
    square_value = params.get('square')
    if isinstance(square_value, dict):
        range_spec = square_value.get('range')
        if isinstance(range_spec, list) and len(range_spec) == 2:
            start, end = range_spec
            try:
                start_int, end_int = int(start), int(end)
            except (ValueError, TypeError):
                raise ValueError(
                    f"Invalid square range values: start={start}, end={end} "
                    f"(must be integers)"
                )
            if start_int > end_int:
                raise ValueError(
                    f"Invalid square range: start={start_int} > end={end_int}. "
                    f"Range must have start <= end"
                )
            expanded = []
            # Detect leading dimension parameters (lda, ldb, ldab, ldafb, etc.)
            leading_dim_params = get_leading_dimension_params(param_order)
            for size in range(start_int, end_int + 1):
                new_params = params.copy()
                new_params.pop('square')
                # Set m, n, and all leading dimension parameters
                # to the same value
                for param_name in ['m', 'n'] + leading_dim_params:
                    if param_name in param_order:
                        new_params[param_name] = size
                # Also set k to match m/n for square matrices
                # (for ormqr, ormlq, etc.)
                if 'k' in param_order and 'k' not in new_params:
                    new_params['k'] = size
                # Also set ihi to match n for full reduction
                # (for gehrd, hseqr, hgeqz, gghrd, etc.)
                if 'ihi' in param_order and 'ihi' not in new_params:
                    new_params['ihi'] = size
                expanded.append(new_params)
            return expanded

    # Check if any parameter has a range
    has_ranges = False
    param_values = {}

    for param_name in param_order:
        if param_name not in params:
            continue

        param_value = params[param_name]

        # Check for dictionary range format: {range: [start, end]}
        if isinstance(param_value, dict) and 'range' in param_value:
            has_ranges = True
            range_spec = param_value['range']
            if not isinstance(range_spec, list) or len(range_spec) != 2:
                raise ValueError(f"Invalid range format for {param_name}: {range_spec}")
            start, end = range_spec
            try:
                start_int, end_int = int(start), int(end)
            except (ValueError, TypeError):
                raise ValueError(
                    f"Invalid range values for {param_name}: "
                    f"start={start}, end={end} (must be integers)"
                )
            if start_int > end_int:
                raise ValueError(
                    f"Invalid range for {param_name}: start={start_int} > end={end_int}. "
                    f"Range must have start <= end"
                )
            param_values[param_name] = list(range(start_int, end_int + 1))
        # Check for string range format: "1-16"
        elif isinstance(param_value, str) and '-' in param_value:
            try:
                start, end = map(int, param_value.split('-', 1))
                if start > end:
                    raise ValueError(
                        f"Invalid range for {param_name}: start={start} > end={end}. "
                        f"Range must have start <= end"
                    )
                has_ranges = True
                param_values[param_name] = list(range(start, end + 1))
            except ValueError as e:
                # If it's our custom ValueError about start > end, re-raise it
                if "Invalid range for" in str(e) and "start=" in str(e):
                    raise
                # Otherwise, not a range, use as-is
                param_values[param_name] = [param_value]
        else:
            # Regular value, use as-is
            param_values[param_name] = [param_value]

    # If no ranges found, return single parameter set
    if not has_ranges:
        return [params]

    # Generate all combinations of parameter values
    param_names = [p for p in param_order if p in param_values]
    value_combinations = itertools.product(*[param_values[p] for p in param_names])

    expanded = []
    for combo in value_combinations:
        new_params = params.copy()
        for param_name, value in zip(param_names, combo):
            # Remove range dict if present, replace with actual value
            if isinstance(new_params.get(param_name), dict):
                new_params.pop(param_name)
            new_params[param_name] = value
        expanded.append(new_params)

    return expanded


def generate_cmake_tests_for_api(api_name, api_def, output_file, global_config=None):
    """Generate CMake test definitions for a single API.

    Args:
        api_name: API name (e.g., getrf).
        api_def: API definition dictionary loaded from YAML.
        output_file: Path to the generated CMake file.
        global_config: Optional global configuration for label groups.

    Raises:
        ValueError: If validation or parameter expansion fails.
        KeyError: If required keys are missing from the API definition.
    """
    # Validate API definition
    check_yaml_api_definition_keys(api_name, api_def)

    param_order = api_def['param_order']
    code_paths = api_def.get('custom_paths', [])

    # Get global configuration
    if global_config is None:
        global_config = {
            'label_groups': {},
            'size_thresholds': None,
            'auto_assign_groups': {}
        }

    label_groups = global_config['label_groups']
    size_thresholds = global_config['size_thresholds']
    auto_assign_groups = global_config['auto_assign_groups']

    with open(output_file, 'w') as out:
        # File header
        out.write(f"# Auto-generated CTest definitions for {api_name.upper()}\n")
        out.write(f"# DO NOT EDIT - Generated from {api_name}.yaml\n\n")

        # Track generated test names to ensure uniqueness
        generated_test_names = set()

        # Generate tests
        for idx, path in enumerate(code_paths):
            # Validate path definition
            validate_path_definition(path, idx, param_order)

            path_name = path['name']
            params = path['params']

            # Expand parameter ranges if present
            expanded_params_list = expand_param_ranges(params, param_order)

            # Get precision string (supports both list and string format)
            prec_raw = path.get('precisions', api_def.get('precisions', []))
            if not prec_raw:
                raise ValueError(
                    f"Path '{path_name}' missing precisions "
                    f"(neither in path nor API definition)"
                )
            prec_string = (''.join(prec_raw) if isinstance(prec_raw, list)
                          else prec_raw)

            # Generate a test for each parameter combination
            for param_idx, expanded_params in enumerate(expanded_params_list):
                # Build test name: API_UPPERCASE_precisions_pathname[_size]
                if len(expanded_params_list) > 1:
                    size_value = (expanded_params.get('m') or
                                  expanded_params.get('n') or
                                  param_idx + 1)
                    test_name = (f"{api_name.upper()}_{prec_string}_"
                                f"{path_name}_{size_value}")
                else:
                    test_name = f"{api_name.upper()}_{prec_string}_{path_name}"

                # Ensure test name uniqueness
                original_test_name = test_name
                counter = 1
                while test_name in generated_test_names:
                    test_name = f"{original_test_name}_{counter}"
                    counter += 1
                generated_test_names.add(test_name)

                cmd_params = ' '.join(
                    str(expanded_params[p]) for p in param_order
                )

                # Build labels from YAML (path-level takes precedence,
                # then API-level, then defaults)
                labels = []

                # Check if path has labels and if they're non-empty
                path_has_labels = 'labels' in path
                path_labels_list = []
                if path_has_labels:
                    path_labels_list = (path['labels']
                                       if isinstance(path['labels'], list)
                                       else [path['labels']])
                    path_has_labels = len(path_labels_list) > 0

                # Use API-level labels if path doesn't have labels
                # or has empty labels
                if not path_has_labels and 'labels' in api_def:
                    api_labels = (api_def['labels']
                                  if isinstance(api_def['labels'], list)
                                  else [api_def['labels']])
                    labels.extend(expand_label_groups(api_labels, label_groups))

                # Add path-specific labels if present and non-empty
                # (takes precedence over API-level)
                if path_has_labels:
                    labels.extend(
                        expand_label_groups(path_labels_list, label_groups)
                    )

                # Always add default labels (uppercase and lowercase
                # for case-insensitive matching)
                api_group = api_def['api_group']
                labels.extend([
                    api_name.upper(),
                    api_name.lower(),
                    api_group.upper(),
                    api_group.lower(),
                    f"precision_{prec_string}",
                    "yaml_generated"
                ])


                # Add individual precision labels for filtering
                precision_map = {
                    's': 'precision_s',
                    'd': 'precision_d',
                    'c': 'precision_c',
                    'z': 'precision_z'
                }
                for prec_char in prec_string:
                    prec_label = precision_map.get(prec_char)
                    if prec_label and prec_label not in labels:
                        labels.append(prec_label)

                # Automatic size-based labeling from parameter thresholds
                size_label = evaluate_size_label(expanded_params, size_thresholds)
                if size_label and size_label not in labels:
                    labels.append(size_label)

                    # Auto-assign group labels based on size label
                    auto_group_labels = auto_assign_group_labels(size_label, auto_assign_groups)
                    for group_label in auto_group_labels:
                        if group_label not in labels:
                            labels.append(group_label)

                # Remove duplicates while preserving order
                seen = set()
                labels = [x for x in labels if not (x in seen or seen.add(x))]

                # Write test definition
                out.write(f"add_test(NAME {test_name}\n")
                out.write(
                    f"         COMMAND ${{CTEST_MAIN_COMMAND}} {api_name} "
                    f"{prec_string} {cmd_params}\n"
                )
                out.write(f"         WORKING_DIRECTORY ${{CTEST_WORKING_DIR}})\n")
                out.write(f"set_tests_properties({test_name} PROPERTIES\n")
                out.write(f"    LABELS \"{';'.join(labels)}\"\n")
                out.write(
                    f"    FAIL_REGULAR_EXPRESSION \"FAIL;No test was run\")\n\n"
                )


def main():
    """CLI entry point for generating CTest definitions from YAML."""
    parser = argparse.ArgumentParser(
        description='Generate CTests from YAML parameters'
    )
    parser.add_argument('--api', help='Generate tests for specific API')
    parser.add_argument(
        '--all', action='store_true', help='Generate tests for all APIs'
    )
    parser.add_argument(
        'output_dir',
        help='Output directory for generated CMake test files'
    )
    args = parser.parse_args()

    script_dir = Path(__file__).parent
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load global configuration (label groups, size thresholds, auto-assign groups)
    global_config = load_global_config(script_dir)

    if args.api:
        yaml_file = script_dir / f"{args.api}.yaml"
        if not yaml_file.exists():
            print(f"Error: {yaml_file} not found", file=sys.stderr)
            return 1

        try:
            with open(yaml_file, 'r') as f:
                data = yaml.safe_load(f)
        except yaml.YAMLError as e:
            print(f"Error: Failed to parse YAML file {yaml_file}: {e}", file=sys.stderr)
            return 1
        except IOError as e:
            print(f"Error: Failed to read file {yaml_file}: {e}", file=sys.stderr)
            return 1

        if data is None:
            print(f"Error: YAML file {yaml_file} is empty or invalid", file=sys.stderr)
            return 1

        api_name = args.api
        if api_name not in data:
            print(f"Error: API '{api_name}' not found in {yaml_file}", file=sys.stderr)
            return 1

        api_def = data[api_name]
        output_file = output_dir / f"{api_name}_tests.cmake"

        try:
            generate_cmake_tests_for_api(
                api_name, api_def, output_file, global_config
            )
            print(
                f"Generated {len(api_def.get('custom_paths', []))} "
                f"tests for {api_name.upper()}"
            )
        except (ValueError, KeyError) as e:
            print(
                f"Error: Failed to generate tests for {api_name}: {e}",
                file=sys.stderr
            )
            return 1

    elif args.all:
        print("Generating tests for all APIs...")
        errors = []
        for yaml_file in script_dir.glob('*.yaml'):
            # Skip non-API definition YAML files
            stem = yaml_file.stem
            if stem in ['auto_generate_label_groups', 'api_source_map']:
                continue
            # Skip temporary test files (files starting with 'test_' or
            # containing '_test', '_backup', '_fixed', '_optimized',
            # '_verify', '_final')
            if (stem.startswith('test_') or
                    '_test' in stem or '_backup' in stem or
                    '_fixed' in stem or '_optimized' in stem or
                    '_verify' in stem or '_final' in stem):
                continue
            api_name = yaml_file.stem
            try:
                with open(yaml_file, 'r') as f:
                    data = yaml.safe_load(f)
            except yaml.YAMLError as e:
                errors.append(f"  {api_name.upper()}: YAML parse error - {e}")
                continue
            except IOError as e:
                errors.append(f"  {api_name.upper()}: File read error - {e}")
                continue

            if data is None:
                errors.append(f"  {api_name.upper()}: Empty or invalid YAML file")
                continue

            if api_name not in data:
                errors.append(f"  {api_name.upper()}: API not found in YAML")
                continue

            api_def = data[api_name]
            output_file = output_dir / f"{api_name}_tests.cmake"
            try:
                generate_cmake_tests_for_api(
                    api_name, api_def, output_file, global_config
                )
            except (ValueError, KeyError) as e:
                errors.append(f"  {api_name.upper()}: {e}")
                continue

        if errors:
            print("\nErrors encountered:", file=sys.stderr)
            for error in errors:
                print(error, file=sys.stderr)
            return 1
    else:
        parser.print_help()
        return 1

    return 0

if __name__ == '__main__':
    exit(main())
